services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      HOSTNAME: 0.0.0.0
    restart: unless-stopped
    ports:
      - "127.0.0.1:3100:3000"
