"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { cn } from "@/lib/utils/cn";

type PhaseTask = {
  id: string;
  title: string;
  description: string | null;
  status: "done" | "active" | "upcoming";
  meta: string;
  requiresApproval: boolean;
};

type PhaseCard = {
  id: string;
  number: number;
  title: string;
  subtitle: string;
  status: "active" | "upcoming" | "done";
  completion: number;
  tasks: PhaseTask[];
};

type Milestone = {
  id: string;
  title: string;
  dateLabel: string;
  status: "on_track" | "upcoming" | "conflict";
  note: string;
};

type ApprovalRequirement = {
  key: string;
  title: string;
  description: string;
  riskLevel: "low" | "medium" | "high";
};

type PlanReviewWorkspaceProps = {
  planTitle: string;
  planSummary: string | null;
  generatedAtLabel: string;
  phases: PhaseCard[];
  milestones: Milestone[];
  approvalRequirements: ApprovalRequirement[];
  assumptions: string[];
  autoFixHref: string;
  editHref: string;
  reviewAssetsHref: string;
  requestChangesHref: string;
};

export function PlanReviewWorkspace({
  planTitle,
  planSummary,
  generatedAtLabel,
  phases,
  milestones,
  approvalRequirements,
  assumptions,
  autoFixHref,
  editHref,
  reviewAssetsHref,
  requestChangesHref,
}: PlanReviewWorkspaceProps) {
  const [view, setView] = useState<"phases" | "timeline">("phases");
  const [sideTab, setSideTab] = useState<"milestones" | "dependencies" | "notes">("milestones");
  const [expandedPhases, setExpandedPhases] = useState<string[]>(
    phases.filter((phase) => phase.status === "active").map((phase) => phase.id),
  );

  const overallCompletion = useMemo(() => {
    if (phases.length === 0) {
      return 0;
    }

    return Math.round(
      phases.reduce((sum, phase) => sum + phase.completion, 0) / phases.length,
    );
  }, [phases]);

  const totalTasks = phases.reduce((sum, phase) => sum + phase.tasks.length, 0);
  const completedTasks = phases.reduce(
    (sum, phase) => sum + phase.tasks.filter((task) => task.status === "done").length,
    0,
  );
  const blockedTasks = phases.reduce(
    (sum, phase) =>
      sum + phase.tasks.filter((task) => task.status === "active" && task.requiresApproval).length,
    0,
  );
  const conflictCount = milestones.filter((milestone) => milestone.status === "conflict").length;

  return (
    <div className="grid h-full grid-cols-[minmax(0,1fr)_360px]">
      <div className="overflow-y-auto px-6 py-6">
        {conflictCount > 0 ? (
          <div className="mb-5 flex items-start gap-3 rounded-lg border border-[#b08a2838] bg-[#b08a2810] px-4 py-3 text-[12px] text-[#e4d8b4]">
            <div className="mt-0.5 text-[#ccaa4a]">!</div>
            <div>
              <strong>Innova detected a scheduling conflict.</strong> One of the downstream milestones overlaps an operator-sensitive checkpoint.
              <Link href={autoFixHref} className="ml-2 font-semibold text-[#ccaa4a] hover:text-[#e2c36b]">
                Auto-fix →
              </Link>
            </div>
          </div>
        ) : null}

        <div className="mb-5 flex items-start justify-between gap-4">
          <div>
            <h1 className="text-[20px] font-semibold tracking-[-0.02em] text-[#eae5dc]">
              {planTitle}
            </h1>
            <p className="mt-2 text-[12px] text-[#9baabf]">
              Auto-generated by Innova · {generatedAtLabel}
            </p>
            {planSummary ? (
              <p className="mt-3 max-w-3xl text-[12px] leading-6 text-[#9baabf]">{planSummary}</p>
            ) : null}
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <button
              type="button"
              onClick={() => setView("timeline")}
              className="rounded-md border border-white/10 px-3 py-2 text-[12px] font-medium text-[#9baabf] transition hover:bg-white/[0.04] hover:text-[#eae5dc]"
            >
              Timeline view
            </button>
            <Link
              href={editHref}
              className="rounded-md border border-white/10 px-3 py-2 text-[12px] font-medium text-[#9baabf] transition hover:bg-white/[0.04] hover:text-[#eae5dc]"
            >
              Edit Plan
            </Link>
            <Link
              href={reviewAssetsHref}
              className="rounded-md bg-[#b08a28] px-4 py-2 text-[12px] font-semibold text-[#07101f] transition hover:bg-[#ccaa4a]"
            >
              Review Assets →
            </Link>
          </div>
        </div>

        <div className="mb-4 flex items-center justify-end">
          <div className="flex gap-[2px] rounded-md border border-white/10 bg-[#111e30] p-1">
            <button
              type="button"
              onClick={() => setView("phases")}
              className={cn(
                "rounded-md px-3 py-1.5 text-[11.5px]",
                view === "phases"
                  ? "border border-white/10 bg-[#162034] text-[#eae5dc]"
                  : "text-[#5e7088]",
              )}
            >
              Phase list
            </button>
            <button
              type="button"
              onClick={() => setView("timeline")}
              className={cn(
                "rounded-md px-3 py-1.5 text-[11.5px]",
                view === "timeline"
                  ? "border border-white/10 bg-[#162034] text-[#eae5dc]"
                  : "text-[#5e7088]",
              )}
            >
              Timeline
            </button>
          </div>
        </div>

        {view === "timeline" ? (
          <div className="mb-6 rounded-xl border border-white/7 bg-[#162034] p-5">
            <div className="mb-4 grid grid-cols-5 gap-2 border-b border-white/7 pb-3 text-center text-[9.5px] uppercase tracking-[0.08em] text-[#5e7088]">
              {phases.map((phase) => (
                <div key={phase.id}>{phase.title}</div>
              ))}
            </div>
            <div className="space-y-4">
              {phases.map((phase) => (
                <div key={phase.id}>
                  <div className="mb-2 flex items-center justify-between text-[11px] text-[#9baabf]">
                    <span>{phase.title}</span>
                    <span>{phase.completion}% complete</span>
                  </div>
                  <div className="h-2 overflow-hidden rounded-full bg-white/[0.06]">
                    <div
                      className={cn(
                        "h-full rounded-full",
                        phase.status === "done" && "bg-[#2d7a58]",
                        phase.status === "active" && "bg-[#b08a28]",
                        phase.status === "upcoming" && "bg-[#49617b]",
                      )}
                      style={{ width: `${Math.max(phase.completion, 6)}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        ) : (
          <div className="space-y-3">
            {phases.map((phase) => {
              const isExpanded = expandedPhases.includes(phase.id);

              return (
                <article key={phase.id} className="overflow-hidden rounded-xl border border-white/10 bg-[#162034]">
                  <button
                    type="button"
                    onClick={() =>
                      setExpandedPhases((current) =>
                        current.includes(phase.id)
                          ? current.filter((id) => id !== phase.id)
                          : [...current, phase.id],
                      )
                    }
                    className="flex w-full items-center gap-3 px-4 py-4 text-left transition hover:bg-white/[0.03]"
                  >
                    <div
                      className={cn(
                        "flex h-7 w-7 items-center justify-center rounded-full border text-[11px] font-semibold",
                        phase.status === "active" &&
                          "border-[#b08a2838] bg-[#b08a2810] text-[#ccaa4a]",
                        phase.status === "upcoming" &&
                          "border-white/10 bg-white/[0.03] text-[#9baabf]",
                        phase.status === "done" &&
                          "border-[#2d7a5840] bg-[#2d7a5812] text-[#9ad0b7]",
                      )}
                    >
                      {phase.number}
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="text-[13px] font-semibold text-[#eae5dc]">{phase.title}</div>
                      <div className="mt-1 text-[11px] text-[#9baabf]">{phase.subtitle}</div>
                    </div>
                    <StatusBadgeLike status={phase.status} />
                    <div className="w-[120px]">
                      <div className="h-2 overflow-hidden rounded-full bg-white/[0.06]">
                        <div
                          className={cn(
                            "h-full rounded-full",
                            phase.status === "done" && "bg-[#2d7a58]",
                            phase.status === "active" && "bg-[#b08a28]",
                            phase.status === "upcoming" && "bg-[#49617b]",
                          )}
                          style={{ width: `${Math.max(phase.completion, 6)}%` }}
                        />
                      </div>
                      <div className="mt-1 text-right text-[9px] text-[#5e7088]">
                        {phase.tasks.filter((task) => task.status === "done").length}/{phase.tasks.length} tasks
                      </div>
                    </div>
                    <div className={cn("text-[#5e7088] transition", isExpanded && "rotate-180")}>⌄</div>
                  </button>

                  {isExpanded ? (
                    <div className="border-t border-white/7 px-4 pb-4 pl-14">
                      {phase.tasks.map((task) => (
                        <div
                          key={task.id}
                          className="flex items-start gap-3 border-b border-white/[0.05] py-3 last:border-b-0"
                        >
                          <div
                            className={cn(
                              "mt-0.5 flex h-4 w-4 items-center justify-center rounded-sm border text-[10px]",
                              task.status === "done" &&
                                "border-[#2d7a5840] bg-[#2d7a5812] text-[#9ad0b7]",
                              task.status !== "done" && "border-white/15 text-[#5e7088]",
                            )}
                          >
                            {task.status === "done" ? "✓" : ""}
                          </div>
                          <div className="min-w-0 flex-1">
                            <div
                              className={cn(
                                "text-[12px]",
                                task.status === "done"
                                  ? "text-[#9baabf] line-through decoration-[#5e7088]"
                                  : "text-[#eae5dc]",
                              )}
                            >
                              {task.title}
                            </div>
                            {task.description ? (
                              <div className="mt-1 text-[10.5px] leading-5 text-[#5e7088]">
                                {task.description}
                              </div>
                            ) : null}
                          </div>
                          <div
                            className={cn(
                              "text-[10.5px]",
                              task.status === "active" && task.requiresApproval
                                ? "text-[#e8c26d]"
                                : "text-[#5e7088]",
                            )}
                          >
                            {task.meta}
                          </div>
                        </div>
                      ))}
                    </div>
                  ) : null}
                </article>
              );
            })}
          </div>
        )}
      </div>

      <aside className="flex flex-col overflow-hidden border-l border-white/7 bg-[#111e30]">
        <div className="flex border-b border-white/7 bg-[#0c1525] px-3 pt-3">
          {[
            { key: "milestones", label: "Milestones" },
            { key: "dependencies", label: "Dependencies" },
            { key: "notes", label: "AI Notes" },
          ].map((tab) => (
            <button
              key={tab.key}
              type="button"
              onClick={() => setSideTab(tab.key as "milestones" | "dependencies" | "notes")}
              className={cn(
                "rounded-t-md px-3 py-2 text-[11.5px]",
                sideTab === tab.key
                  ? "border border-b-0 border-white/10 bg-[#111e30] font-medium text-[#eae5dc]"
                  : "text-[#5e7088]",
              )}
            >
              {tab.label}
            </button>
          ))}
        </div>
        <div className="flex-1 overflow-y-auto p-4">
          {sideTab === "milestones" ? (
            <div className="space-y-3">
              <div className="text-[11px] font-semibold uppercase tracking-[0.08em] text-[#5e7088]">
                Key Milestones
              </div>
              {milestones.map((milestone) => (
                <div key={milestone.id} className="flex items-start gap-3 border-b border-white/[0.05] py-3 last:border-b-0">
                  <div
                    className={cn(
                      "mt-1 h-2.5 w-2.5 rounded-full",
                      milestone.status === "on_track" && "bg-[#b08a28]",
                      milestone.status === "upcoming" && "bg-[#6d8eb0]",
                      milestone.status === "conflict" && "bg-[#c9973a]",
                    )}
                  />
                  <div className="min-w-0 flex-1">
                    <div className="text-[12px] font-medium text-[#eae5dc]">{milestone.title}</div>
                    <div className="mt-1 text-[11px] text-[#9baabf]">{milestone.dateLabel}</div>
                    <div
                      className={cn(
                        "mt-1 text-[10.5px]",
                        milestone.status === "conflict" ? "text-[#e8c26d]" : "text-[#5e7088]",
                      )}
                    >
                      {milestone.note}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          ) : null}

          {sideTab === "dependencies" ? (
            <div className="space-y-3">
              <div className="text-[11px] font-semibold uppercase tracking-[0.08em] text-[#5e7088]">
                Approval Dependencies
              </div>
              {approvalRequirements.length > 0 ? (
                approvalRequirements.map((requirement) => (
                  <div key={requirement.key} className="rounded-xl border border-white/7 bg-[#162034] p-4">
                    <div className="mb-2 flex items-start justify-between gap-3">
                      <div className="text-[12px] font-semibold text-[#eae5dc]">{requirement.title}</div>
                      <span
                        className={cn(
                          "rounded-sm border px-2 py-1 text-[9px] font-semibold uppercase tracking-[0.06em]",
                          requirement.riskLevel === "high" &&
                            "border-[#9b3a3a44] bg-[#9b3a3a12] text-[#f1bcbc]",
                          requirement.riskLevel === "medium" &&
                            "border-[#c9973a40] bg-[#c9973a12] text-[#e8c26d]",
                          requirement.riskLevel === "low" &&
                            "border-white/10 bg-white/[0.03] text-[#9baabf]",
                        )}
                      >
                        {requirement.riskLevel}
                      </span>
                    </div>
                    <p className="text-[11px] leading-5 text-[#9baabf]">{requirement.description}</p>
                  </div>
                ))
              ) : (
                <div className="rounded-lg border border-dashed border-white/10 bg-[#162034] px-4 py-4 text-[12px] leading-6 text-[#9baabf]">
                  Approval dependencies will appear here once the plan includes gated execution items.
                </div>
              )}
            </div>
          ) : null}

          {sideTab === "notes" ? (
            <div className="space-y-3">
              <div className="text-[11px] font-semibold uppercase tracking-[0.08em] text-[#5e7088]">
                Plan Health
              </div>
              <HealthMeter label="Overall completion" value={`${overallCompletion}%`} width={overallCompletion} tone="gold" />
              <HealthMeter
                label="Tasks completed"
                value={`${completedTasks}/${totalTasks}`}
                width={totalTasks === 0 ? 0 : Math.round((completedTasks / totalTasks) * 100)}
                tone="blue"
              />
              <div className="space-y-2 pt-1">
                <div className="flex items-center gap-2 text-[11px] text-[#9baabf]">
                  <span className="h-2 w-2 rounded-full bg-[#c9973a]" />
                  {blockedTasks} approval-sensitive tasks
                </div>
                <div className="flex items-center gap-2 text-[11px] text-[#9baabf]">
                  <span className="h-2 w-2 rounded-full bg-[#6d8eb0]" />
                  {assumptions.length} active planning assumptions
                </div>
                <div className="flex items-center gap-2 text-[11px] text-[#9baabf]">
                  <span className="h-2 w-2 rounded-full bg-[#b08a28]" />
                  {conflictCount} milestone conflicts
                </div>
              </div>
            </div>
          ) : null}
        </div>

        <div className="flex gap-2 border-t border-white/7 p-4">
          <Link
            href={requestChangesHref}
            className="rounded-md border border-white/10 px-3 py-2 text-[11.5px] font-semibold text-[#9baabf] transition hover:bg-white/[0.04] hover:text-[#eae5dc]"
          >
            Request Changes
          </Link>
          <Link
            href={reviewAssetsHref}
            className="flex-1 rounded-md bg-[#b08a28] px-3 py-2 text-center text-[11.5px] font-semibold text-[#07101f] transition hover:bg-[#ccaa4a]"
          >
            Review Assets →
          </Link>
        </div>
      </aside>
    </div>
  );
}

function StatusBadgeLike({ status }: { status: "active" | "upcoming" | "done" }) {
  return (
    <span
      className={cn(
        "rounded-sm border px-2 py-1 text-[9px] font-semibold uppercase tracking-[0.06em]",
        status === "active" && "border-[#b08a2838] bg-[#b08a2810] text-[#ccaa4a]",
        status === "upcoming" && "border-white/10 bg-white/[0.03] text-[#9baabf]",
        status === "done" && "border-[#2d7a5840] bg-[#2d7a5812] text-[#9ad0b7]",
      )}
    >
      {status === "done" ? "Complete" : status === "active" ? "Active" : "Upcoming"}
    </span>
  );
}

function HealthMeter({
  label,
  value,
  width,
  tone,
}: {
  label: string;
  value: string;
  width: number;
  tone: "gold" | "blue";
}) {
  return (
    <div>
      <div className="mb-1 flex items-center justify-between text-[11px] text-[#9baabf]">
        <span>{label}</span>
        <span>{value}</span>
      </div>
      <div className="h-2 overflow-hidden rounded-full bg-white/[0.06]">
        <div
          className={cn("h-full rounded-full", tone === "gold" ? "bg-[#b08a28]" : "bg-[#6d8eb0]")}
          style={{ width: `${Math.max(width, 0)}%` }}
        />
      </div>
    </div>
  );
}
